<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNbTicketsJournalier($datepickerValue) {

         $qb = $this->createQueryBuilder('r')
             ->where('r.paye = 1')
             ->andWhere('r.date = :datepickerValue')
             ->setParameter('datepickerValue', $datepickerValue)
             ->addSelect('rt')
             ->leftJoin('r.ticket', 'rt')
             ->andWhere('rt.paye = 1');

         $qb->select($qb->expr()->count('rt'));

        return (int) $qb->getQuery()->getSingleScalarResult();

    }

}
